###뿌리기API
POST http://localhost:8080/v1/seeds
Content-Type: application/json;charset=UTF-8
X-USER-ID: 2
X-ROOM-ID: room2

{
  "seedingAmount" : 100,
  "receivedPersonCount": 3
}

###받기API
PUT http://localhost:8080/v1/seeds
Content-Type: application/json;charset=UTF-8
X-USER-ID: 1
X-ROOM-ID: room2

{
  "token" : "Hcw"
}

###조회 API
GET http://localhost:8080/v1/seeds
 ?token=Hcw
Content-Type: application/json;charset=UTF-8
X-USER-ID: 2

###


